config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :beers
  resources :orders, only: %i[index create]
  resources :users, only: %i[show edit update] do
    get 'sales', to: 'users#sale'
    get 'for_sale', to: 'users#for_sale'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  validates :name, :description, :category, :price, :quantity, presence:true

  include PgSearch::Model
  pg_search_scope :search_beers,
                  against: %i[name category description],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :beer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :beers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_query

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def set_query
    if params[:query].blank?
      @beers = policy_scope(Beer)
    else
      @beers = policy_scope(Beer.search_beers(params[:query]))
      render 'beers/index'
    end
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].blank?
      @beers = policy_scope(Beer).where.not(quantity:0)
    else
      @beers = policy_scope(Beer.search_beers(params[:query])).where.not(quantity:0)
      render 'index'
    end
  end

  def show
    # set_beer - Substituido pelo before_action
    @order = Order.new
  end

  def edit
  end

  def update
    @beer.update(beer_params)
    redirect_to beer_path(@beer)
  end

  def new
    @beer = Beer.new
    authorize @beer
  end

  def create
    @beer = Beer.new(beer_params)
    @beer.user = current_user
    authorize @beer

    if @beer.save
      redirect_to @beer, notice: 'Beer was successfully created into the catalog.'
    else
      render :new
    end
  end

  def destroy
    @beer.destroy
    redirect_to beers_url, notice: 'Beer has been removed.'
  end

  private

  def set_beer
    @beer = Beer.find(params[:id])
    authorize @beer
  end

  def beer_params
    params.require(:beer).permit(:name, :category, :price, :description, :quantity, :photo)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_query, only: %i[index]

  def index
    @orders = policy_scope(Order.where(user_id: current_user))
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.date = Time.now
    authorize @order

    if @order.save
      beer = Beer.find(order_params[:beer_id])
      if @order.quantity == 0 
        redirect_to beer_path(@order.beer_id), notice: 'Quantity must be greater than zero.'  
      elsif beer.quantity >= @order.quantity  
        beer.update(quantity: beer.quantity-@order.quantity)
        redirect_to orders_path, notice: 'Order was successfully created into the catalog.'
      else
        redirect_to beer_path(@order.beer_id), notice: 'Quantity not available.'  
      end  
    else
      redirect_to beer_path(@order.beer_id), notice: 'Order was not created'
    end
  
     

  end

  def order_params
    params.require(:order).permit(:quantity, :beer_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    redirect_to beers_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  before_action :set_user_by_id, only: %i[sale for_sale]

  def sale
    @sales = Order.joins(:beer).where(beers: { user_id: current_user }).reject { |order| order.user_id == current_user.id }
  end

  def for_sale
    @for_sale = Beer.where(beers: { user_id: current_user })
  end

  def show
    # set_user - Substituido pelo before_action
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def set_user_by_id
    @user = User.find(params[:user_id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(:full_name, :address, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/_form.html.erb
<%= simple_form_for(@beer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :description %>
    <%= f.input :quantity %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <div class="d-flex justify-content-between col-md-4 px-0">
      <%= f.button :submit, "Create Sale", class: "btn btn-warning text-white" %>
      <%= link_to 'Back', @beer, class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

app/views/beers/edit.html.erb
<div class="container">
  <h1>Edit Beer</h1>

  <div class="row justify-content-center">
    <div class="col col-lg-10">
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/beers/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.05),rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1536584979139-dde0784c7c75?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&dl=markus-spiske-0376tfLb89c-unsplash.jpg&w=1920')">
  <div class="container">
    <h1>Beer Marketplace</h1>
    <p>COMPRE E VENDA CERVEJAS ARTESANAIS</p>
    <p><span id="banner-typed-text"></span></p>
  </div>
</div>

<div class="container">
  <div class="row row-cols-1 row-cols-md-4">
    <% @beers.each do |beer| %>
      <div class="col mb-4 index-card">
        <div class="card h-100 border-0 p-2">
          <%= cl_image_tag(beer.photo.key, :height=>250, :crop=>"fill") if beer.photo.attached? %>
          <div class="card-body">
            <h5 class="card-title text-secondary mb-1"><%= beer.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= beer.category %></h6>
            <p class="text-center font-weight-bold">R$ <%= sprintf('%.2f', beer.price) %></p>
            <a href="<%= beer_path(beer) %>" class="stretched-link"></a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/beers/new.html.erb
<div class="container">
  <h1>Sell Beer</h1>

  <div class="row justify-content-center">
    <div class="col col-lg-10">
      <%= render 'form', beer: @beer %>
    </div>
  </div>

</div>

app/views/beers/show.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<div class="container mt-5">
  <%# Source: https://codepen.io/ThomasDaubenton/pen/EwVEjE %>
  <div class="card-container">
    <div class="row">
      <div class="left col-md-6">
        <%= cl_image_tag(@beer.photo.key, :height=>250, :crop=>"fill") if @beer.photo.attached? %>
      </div>
      <div class="right col-md-6">
        <h4 class="categorie"><%= @beer.name %></h4>
        <h3 class="product"><%= @beer.category %></h3>
        <p class="desc"><%= @beer.description %></p>
        <%= render "orders/form", beer:@beer  %></h4> 
        <p class="price">R$ <%= sprintf('%.2f', @beer.price)%></p>
         <%# <%=link_to "Buy Now", orders_path(beer_id: @beer.id), method: :post, class: "buy" %>
      </div>
    </div>
  </div>

  <% if user_signed_in? && policy(@beer).edit? %>
    <%# Show the edit button only to the owner or administrator, per beer policy %>
    <%= link_to 'Edit', edit_beer_path(@beer) %>
    <%= link_to 'Delete', beer_path(@beer), method: :delete, data: { confirm: "Are you sure you want to remove this beer?"}, class: 'text-danger' %>
  <% end %>
  <%= link_to 'Back', beers_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beer Marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
 
  <div class="form-row align-items-center ml-1">

    Quantity: <%= f.input :quantity, input_html: {value:0}, label: false, id:"quantity"  %>( <span> <%= @beer.quantity %> available)</span>
    <%= f.input :beer_id, input_html: {value:beer.id}, as: :hidden %>
  </div>
  

  <div class="form-actions">
    <%= f.button :submit, "Buy Now", class: "buy" %>
  </div>
<% end %>

app/views/orders/index.html.erb
<div class="container">
  <h1>My Beer Orders</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Date of Purchase</th>
        <th scope="col">Ticket Number</th>
        <th scope="col">Beer Title</th>
        <th scope="col">Quantity</th>
        <th scope="col">Invoiced Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.date %></td>
          <td><%= '%05d' % order.id %></td>
          <td><%= order.beer.name %></td>
          <td><%= order.quantity %></td>
          <td><%= '%.2f' % (order.beer.price * order.quantity) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row justify-content-between">
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
      <div class="footer-copyright">
        This web app was made with water, malt and hops at Le Wagon.
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon shadow">
  <div class="container my-3">
    <%= link_to beers_path, class: "navbar-brand" do %>
      <%= image_tag "logo-beer.png" %>
    <% end %>

    <div class="main">
      <form action=<%beers_path%>>
        <div class="input-group">
          <input type="text" name="query" class="form-control" placeholder="Busque cervejas, estilos e mais...">
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
      </form>
    </div>

    <% if false %>
    <%= form_tag beers_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Busque cerevejas, estilos e mais..."
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <% if user_signed_in? %>
            <%= link_to "My Profile", user_path(current_user), class: "nav-link" %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sell Beer', new_beer_path, class:  "nav-link btn btn-warning text-white" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "refrigerator.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My Orders", orders_path, class: "dropdown-item" %>
              <%= link_to "My Sales", user_sales_path(user_id: current_user), class: "dropdown-item" %>
              <%= link_to "My Offers", user_for_sale_path(user_id: current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container-lg">
  <h2 class="display-4 my-4">Update your profile</h2>

  <%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :full_name, label_html: { class: "col-lg-2 col-form-label font-weight-bold"}, input_html: { class: "col-md-4 form-control" } %>
    <%= f.input :address, label_html: { class: "col-lg-2 col-form-label font-weight-bold"}, input_html: { class: "col-md-4 form-control" } %>
    <%= f.input :age, label_html: { class: "col-lg-2 col-form-label font-weight-bold"}, input_html: { class: "col-md-4 form-control" } %>
  </div>

  <div class="form-actions">
    <div class="d-flex justify-content-between col-md-4 px-0">
        <%= f.button :submit, class: "btn btn-success text-light" %>
        <%= link_to 'Back', @user, class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>
</div>

app/views/users/for_sale.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>My Beer For Sale</h1>
  <div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Beer</th>
          <th scope="col">Price</th>
          <th scope="col">Category</th>
          <th scope="col">Description</th>
          <th scope="col">Quantity</th>
          <th scope="col">Edit</th>
        </tr>
      </thead>
      <tbody>
        <% @for_sale.each do |beer| %>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.price %></td>
            <td><%= beer.category %></td>
            <td><%= beer.description %></td>
            <td><%= beer.quantity %></td>
            <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/sale.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>My Beer Sales</h1>
  <div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Ticket Number</th>
          <th scope="col">Beer</th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
        </tr>
      </thead>
      <tbody>
        <% if @sales == nil %>
          <p>Sell a beer first!</p>
        <% else @sales.each do |sale| %>
          <tr>
            <td><%= sale.date %></td>
            <td><%= '%05d' % sale.id %></td>
            <td><%= sale.beer.name %></td>
            <td><%= sale.quantity %></td>
            <td><%=  '%.2f' % (sale.beer.price * sale.quantity) %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2 class="display-4 my-4">My profile</h2>

  <form action="/users" accept-charset="UTF-8" method="post">
    <div class="row form-group">
      <label class="col-6 col-md-2 col-form-label text-left">E-mail</label>
      <div class="col-6 col-md-4">
        <input class="form-control" type="text" placeholder="<%= @user.email %>" readonly>
      </div>
    </div>
    <div class="row form-group align-items-center">
      <label class="col-sm-2 col-form-label text-left">Full name</label>
      <div class="col-sm-4">
        <p class="mb-0"><%= @user.full_name %></p>
      </div>
    </div>
    <div class="row form-group align-items-center">
      <label class="col-sm-2 col-form-label text-left">Address</label>
      <div class="col-sm-4">
        <p class="mb-0"><%= @user.address %></p>
      </div>
    </div>
    <div class="row form-group align-items-center">
      <label class="col-sm-2 col-form-label text-left">Age</label>
      <div class="col-sm-4">
        <p class="mb-0"><%= @user.age %></p>
      </div>
    </div>
    <br>
    <%= link_to 'Update profile', edit_user_path(@user), class: "btn btn-outline-secondary" %>
    </form>
    <br>
    <br>
  <div class="container d-flex">
    <div class="row">
      <div class="col-sm-3">
        <%= link_to 'My Beer Orders', orders_path, class: "btn btn-warning text-white" %>
      </div>
      <div class="col-sm-3">
        <%= link_to 'My Beer Sales', user_sales_path(user_id: current_user), class: "btn btn-warning text-white" %>
      </div>
      <div class="col-sm-3">
        <%= link_to 'My Beer For Sale', user_for_sale_path(user_id: current_user), class: "btn btn-warning text-white" %>
      </div>
    </div>
  </div>
</div>